version: "3.5"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    restart: always
    env_file: ./.env
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - backend
    restart: always
  
networks:
  backend-network:
    driver: bridge