version: "3.5"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    env_file: ./.env
    depends_on:
      - database
    restart: always
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
      - database
    restart: always
  database:
    container_name: database
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    restart: always