version: "3.5"
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app
    env_file: ./.env
    depends_on:
      - database
    environment:
      - MONGODB_URI="mongodb://localhost:27017"
    links:
      - database
    restart: always

  database:
    container_name: database
    command: mongod --quiet --logpath /dev/null
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db
    restart: always