GET http://localhost:8081/api/topics HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWVnYW1vbnN0ZXJjcmFmdEBnbWFpbC5jb20iLCJpYXQiOjE2NTQ4NTM4MzQsImV4cCI6MTY1NTExMzAzNH0.nR-QI9w0P_bobKyq_aJIMkZ5umI5C4lyLzEhQZp5OG0