DELETE http://localhost:8081/api/topics/aaa HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtYWlsIjoibWVnYW1vbnN0ZXJjcmFmdEBnbWFpbC5jb20iLCJpYXQiOjE2NTA4Nzc4MzYsImV4cCI6MTY1MTA1MDYzNn0.rTr6MN2bc761xcUXe72HfvQqjy5GZxewjJKTfHHXuJI